name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]  # Specify a stable version

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Clean npm cache and reinstall
      run: |
        rm -rf node_modules
        rm package-lock.json
        npm cache clean --force
        npm install
    - run: npm run build --if-present
    - name: Build Docker image
      run: docker build -t face:latest .
